Add test showing failure around internal method generation
AutoFixture was unable to create an instance from
NSubstituteRequest: Microsoft.Diagnostics.Runtime.ClrHeap
because creation unexpectedly failed with exception.

Request path:
 Microsoft.Diagnostics.Runtime.ClrHeap heap
   Microsoft.Diagnostics.Runtime.ClrHeap
     NSubstituteRequest: Microsoft.Diagnostics.Runtime.ClrHeap

System.TypeLoadException: Method 'EnumerateObjectReferences'
in type 'Castle.Proxies.ClrHeapProxy' from assembly
 'DynamicProxyGenAssembly2, Version=0.0.0.0 ...
does not have an implementation.