Generate better exceptions with bad dump files
- Catch a stray AggregateException when a symbol server is not reachable.
- Prevent System.OverflowException from creeping out of `ElfFile.TryGetExportSymbol`.
- Generate a more helpful exception message when we encounter a bad dump file.

This is the exception message we generate when `CLRDataCreateInstance` fails with exception code 0x80131c4f:

Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: 'Failure loading DAC: CreateDacInstance failed 0x80131c4f, which usually indicates the dump file was taken incorrectly.'

While the root cause will not always be an incorrectly generated dump file, it is the right first thing to investigate.