Feature/175 introduce unit tests (#181)
* Introduce unitTest project

* Add test showing failure around internal method generation

AutoFixture was unable to create an instance from
NSubstituteRequest: Microsoft.Diagnostics.Runtime.ClrHeap
because creation unexpectedly failed with exception.

Request path:
 Microsoft.Diagnostics.Runtime.ClrHeap heap
   Microsoft.Diagnostics.Runtime.ClrHeap
     NSubstituteRequest: Microsoft.Diagnostics.Runtime.ClrHeap

System.TypeLoadException: Method 'EnumerateObjectReferences'
in type 'Castle.Proxies.ClrHeapProxy' from assembly
 'DynamicProxyGenAssembly2, Version=0.0.0.0 ...
does not have an implementation.

* Increase visibility for ClrHeap internal abstract methods

Having public abstraction with internal abstract members
prevents implementations from outside assemblies
leading to mocking frameworks troubles.

Mock generation needs to fulfil all the abstraction members
thus must get a change to touch those.

* Increase visibility for ClrType abstract internal property

* Increase visibility for DataTarget abstract internal property